# Generated by Django 4.0.5 on 2022-11-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VotingTurnOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('cDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'VotingIS',
            },
        ),
    ]
