# Generated by Django 4.0.5 on 2022-11-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartiesRegistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('locality', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('partysymbol', models.FileField(upload_to='uploads/')),
                ('partyname', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'PartiesRegistrations',
            },
        ),
        migrations.CreateModel(
            name='VoterRegistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('loginid', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('locality', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=100)),
                ('aadhar', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'VoterRegistrations',
            },
        ),
        migrations.CreateModel(
            name='VotingPollModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar', models.CharField(max_length=100, unique=True)),
                ('candidate_id', models.IntegerField()),
                ('candidateName', models.CharField(max_length=100)),
                ('constituency', models.CharField(max_length=100)),
                ('partyname', models.CharField(max_length=100)),
                ('vote', models.IntegerField()),
            ],
            options={
                'db_table': 'VotingTable',
            },
        ),
    ]
